const source = Deno.readTextFileSync(new URL('../ConnectionEvents.js', import.meta.url))
const { newState, shouldShow } = new Function(source + '; return { newState, shouldShow }')()
function check(name, value, expected) { if (value !== expected) throw new Error(name) }
let state = newState()
check('shell reload while connected is quiet', shouldShow(state, true, 0), false)
check('battery updates are quiet', shouldShow(state, true, 100), false)
check('disconnect is quiet', shouldShow(state, false, 200), false)
check('connection displays once', shouldShow(state, true, 300), true)
check('repeated status is quiet', shouldShow(state, true, 400), false)
shouldShow(state, false, 500)
check('short control recovery is quiet', shouldShow(state, true, 600), false)
shouldShow(state, false, 16000)
check('later connection displays', shouldShow(state, true, 17000), true)
state = newState()
check('startup disconnected is quiet', shouldShow(state, false, 0), false)
check('first real connection displays', shouldShow(state, true, 1), true)
console.log('connection-events.test.js: all checks passed')
