const source = Deno.readTextFileSync(new URL('../ConnectionEvents.js', import.meta.url))
const { newState, shouldShow } = new Function(source + '; return { newState, shouldShow }')()
function check(name, value, expected) { if (value !== expected) throw new Error(name) }
let state = newState()
check('shell reload while connected is quiet', shouldShow(state, true, 2, 0), false)
check('battery updates are quiet', shouldShow(state, true, 2, 100), false)
check('disconnect is quiet', shouldShow(state, false, 2, 200), false)
check('connection displays once', shouldShow(state, true, 2, 300), true)
check('repeated status is quiet', shouldShow(state, true, 2, 400), false)
shouldShow(state, false, 2, 500)
check('short control recovery is quiet', shouldShow(state, true, 2, 600), false)
shouldShow(state, false, 2, 16000)
check('later connection displays', shouldShow(state, true, 2, 17000), true)

state = newState()
check('startup disconnected is quiet', shouldShow(state, false, 2, 0), false)
check('first real connection displays', shouldShow(state, true, 2, 1), true)

state = newState()
check('shell reload with an open lid is quiet', shouldShow(state, false, 0, 0), false)
check('repeated open advertisements are quiet', shouldShow(state, false, 0, 100), false)
check('closing the lid is quiet', shouldShow(state, false, 1, 200), false)
check('closed to open displays once', shouldShow(state, false, 0, 300), true)
check('another open advertisement is quiet', shouldShow(state, false, 0, 400), false)
check('audio connection after opening is deduplicated', shouldShow(state, true, 0, 500), false)

state = newState()
check('unknown to open is not proof of an opening', shouldShow(state, false, 2, 0), false)
check('unknown lid remains quiet', shouldShow(state, false, 0, 100), false)
check('known closed lid remains quiet', shouldShow(state, false, 1, 200), false)
check('later known opening displays', shouldShow(state, false, 0, 300), true)
shouldShow(state, false, 1, 16000)
check('opening after the cooldown displays again', shouldShow(state, false, 0, 17000), true)
console.log('connection-events.test.js: all checks passed')
